import type { Driver } from './types';

export const CONSTRUCTOR_COLORS: Record<string, string> = {
  'Red Bull': '#3671C6',
  Ferrari: '#E8002D',
  Mercedes: '#27F4D2',
  McLaren: '#FF8000',
  'Aston Martin': '#229971',
  Alpine: '#FF87BC',
  Williams: '#64C4FF',
  'Racing Bulls': '#6692FF',
  Haas: '#B6BABD',
  Audi: '#52E252',
  Cadillac: '#CC0000',
};

export const CONSTRUCTOR_SHORT: Record<string, string> = {
  'Red Bull': 'RBR',
  Ferrari: 'FER',
  Mercedes: 'MER',
  McLaren: 'MCL',
  'Aston Martin': 'AMR',
  Alpine: 'ALP',
  Williams: 'WIL',
  'Racing Bulls': 'RB',
  Haas: 'HAA',
  Audi: 'AUD',
  Cadillac: 'CAD',
};

export const DRIVERS: Record<string, Driver> = {
  VER: {
    id: 'VER',
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 33,
    constructor: 'Red Bull',
    nationality: 'Netherlands',
    flag: '🇳🇱',
  },
  HAD: {
    id: 'HAD',
    name: 'Isack Hadjar',
    shortName: 'HAD',
    number: 6,
    constructor: 'Red Bull',
    nationality: 'France',
    flag: '🇫🇷',
  },
  LEC: {
    id: 'LEC',
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    constructor: 'Ferrari',
    nationality: 'Monaco',
    flag: '🇲🇨',
  },
  HAM: {
    id: 'HAM',
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    constructor: 'Ferrari',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  RUS: {
    id: 'RUS',
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    constructor: 'Mercedes',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  ANT: {
    id: 'ANT',
    name: 'Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    constructor: 'Mercedes',
    nationality: 'Italy',
    flag: '🇮🇹',
  },
  NOR: {
    id: 'NOR',
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 4,
    constructor: 'McLaren',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  PIA: {
    id: 'PIA',
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    constructor: 'McLaren',
    nationality: 'Australia',
    flag: '🇦🇺',
  },
  ALO: {
    id: 'ALO',
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    constructor: 'Aston Martin',
    nationality: 'Spain',
    flag: '🇪🇸',
  },
  STR: {
    id: 'STR',
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    constructor: 'Aston Martin',
    nationality: 'Canada',
    flag: '🇨🇦',
  },
  GAS: {
    id: 'GAS',
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    constructor: 'Alpine',
    nationality: 'France',
    flag: '🇫🇷',
  },
  COL: {
    id: 'COL',
    name: 'Franco Colapinto',
    shortName: 'COL',
    number: 43,
    constructor: 'Alpine',
    nationality: 'Argentina',
    flag: '🇦🇷',
  },
  ALB: {
    id: 'ALB',
    name: 'Alex Albon',
    shortName: 'ALB',
    number: 23,
    constructor: 'Williams',
    nationality: 'Thailand',
    flag: '🇹🇭',
  },
  SAI: {
    id: 'SAI',
    name: 'Carlos Sainz',
    shortName: 'SAI',
    number: 55,
    constructor: 'Williams',
    nationality: 'Spain',
    flag: '🇪🇸',
  },
  LAW: {
    id: 'LAW',
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    constructor: 'Racing Bulls',
    nationality: 'New Zealand',
    flag: '🇳🇿',
  },
  LIN: {
    id: 'LIN',
    name: 'Arvid Lindblad',
    shortName: 'LIN',
    number: 34,
    constructor: 'Racing Bulls',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  OCO: {
    id: 'OCO',
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    constructor: 'Haas',
    nationality: 'France',
    flag: '🇫🇷',
  },
  BEA: {
    id: 'BEA',
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    constructor: 'Haas',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  HUL: {
    id: 'HUL',
    name: 'Nico Hülkenberg',
    shortName: 'HUL',
    number: 27,
    constructor: 'Audi',
    nationality: 'Germany',
    flag: '🇩🇪',
  },
  BOR: {
    id: 'BOR',
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    constructor: 'Audi',
    nationality: 'Brazil',
    flag: '🇧🇷',
  },
  BOT: {
    id: 'BOT',
    name: 'Valtteri Bottas',
    shortName: 'BOT',
    number: 77,
    constructor: 'Cadillac',
    nationality: 'Finland',
    flag: '🇫🇮',
  },
  PER: {
    id: 'PER',
    name: 'Sergio Perez',
    shortName: 'PER',
    number: 11,
    constructor: 'Cadillac',
    nationality: 'Mexico',
    flag: '🇲🇽',
  },
};

// Reverse lookup: full driver name → driver code (for mapping API responses)
// Includes aliases for FastF1 name variants (ASCII, full legal names, etc.)
const DRIVER_NAME_ALIASES: Record<string, string> = {
  'Nico Hulkenberg': 'HUL', // FastF1 strips umlaut
  'Alexander Albon': 'ALB', // FastF1 uses legal name
};

export const DRIVER_BY_NAME: Record<string, string> = {
  ...Object.fromEntries(Object.entries(DRIVERS).map(([code, driver]) => [driver.name, code])),
  ...DRIVER_NAME_ALIASES,
};
