import type { Driver } from './types';

export const CONSTRUCTOR_COLORS: Record<string, string> = {
  'Red Bull': '#3671C6',
  Ferrari: '#E8002D',
  Mercedes: '#27F4D2',
  McLaren: '#FF8000',
  'Aston Martin': '#229971',
  Alpine: '#FF87BC',
  Williams: '#64C4FF',
  'Racing Bulls': '#6692FF',
  Haas: '#B6BABD',
  'Kick Sauber': '#52E252',
};

export const CONSTRUCTOR_SHORT: Record<string, string> = {
  'Red Bull': 'RBR',
  Ferrari: 'FER',
  Mercedes: 'MER',
  McLaren: 'MCL',
  'Aston Martin': 'AMR',
  Alpine: 'ALP',
  Williams: 'WIL',
  'Racing Bulls': 'RB',
  Haas: 'HAA',
  'Kick Sauber': 'SAU',
};

export const DRIVERS: Record<string, Driver> = {
  VER: {
    id: 'VER',
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 1,
    constructor: 'Red Bull',
    nationality: 'Netherlands',
    flag: '🇳🇱',
  },
  LAW: {
    id: 'LAW',
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    constructor: 'Red Bull',
    nationality: 'New Zealand',
    flag: '🇳🇿',
  },
  LEC: {
    id: 'LEC',
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    constructor: 'Ferrari',
    nationality: 'Monaco',
    flag: '🇲🇨',
  },
  HAM: {
    id: 'HAM',
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    constructor: 'Ferrari',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  RUS: {
    id: 'RUS',
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    constructor: 'Mercedes',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  ANT: {
    id: 'ANT',
    name: 'Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    constructor: 'Mercedes',
    nationality: 'Italy',
    flag: '🇮🇹',
  },
  NOR: {
    id: 'NOR',
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 4,
    constructor: 'McLaren',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  PIA: {
    id: 'PIA',
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    constructor: 'McLaren',
    nationality: 'Australia',
    flag: '🇦🇺',
  },
  ALO: {
    id: 'ALO',
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    constructor: 'Aston Martin',
    nationality: 'Spain',
    flag: '🇪🇸',
  },
  STR: {
    id: 'STR',
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    constructor: 'Aston Martin',
    nationality: 'Canada',
    flag: '🇨🇦',
  },
  GAS: {
    id: 'GAS',
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    constructor: 'Alpine',
    nationality: 'France',
    flag: '🇫🇷',
  },
  DOO: {
    id: 'DOO',
    name: 'Jack Doohan',
    shortName: 'DOO',
    number: 7,
    constructor: 'Alpine',
    nationality: 'Australia',
    flag: '🇦🇺',
  },
  ALB: {
    id: 'ALB',
    name: 'Alex Albon',
    shortName: 'ALB',
    number: 23,
    constructor: 'Williams',
    nationality: 'Thailand',
    flag: '🇹🇭',
  },
  SAI: {
    id: 'SAI',
    name: 'Carlos Sainz',
    shortName: 'SAI',
    number: 55,
    constructor: 'Williams',
    nationality: 'Spain',
    flag: '🇪🇸',
  },
  TSU: {
    id: 'TSU',
    name: 'Yuki Tsunoda',
    shortName: 'TSU',
    number: 22,
    constructor: 'Racing Bulls',
    nationality: 'Japan',
    flag: '🇯🇵',
  },
  HAD: {
    id: 'HAD',
    name: 'Isack Hadjar',
    shortName: 'HAD',
    number: 6,
    constructor: 'Racing Bulls',
    nationality: 'France',
    flag: '🇫🇷',
  },
  OCO: {
    id: 'OCO',
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    constructor: 'Haas',
    nationality: 'France',
    flag: '🇫🇷',
  },
  BEA: {
    id: 'BEA',
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    constructor: 'Haas',
    nationality: 'Great Britain',
    flag: '🇬🇧',
  },
  HUL: {
    id: 'HUL',
    name: 'Nico Hülkenberg',
    shortName: 'HUL',
    number: 27,
    constructor: 'Kick Sauber',
    nationality: 'Germany',
    flag: '🇩🇪',
  },
  BOR: {
    id: 'BOR',
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    constructor: 'Kick Sauber',
    nationality: 'Brazil',
    flag: '🇧🇷',
  },
};

// Reverse lookup: full driver name → driver code (for mapping API responses)
export const DRIVER_BY_NAME: Record<string, string> = Object.fromEntries(
  Object.entries(DRIVERS).map(([code, driver]) => [driver.name, code]),
);
