// Generated by scripts/generate_public_client.py. Do not edit manually.
export interface Coverage {
  state: 'complete' | 'partial' | 'unknown' | 'empty';
  available: number | null;
  expected: number | null;
  reason: string | null;
}
export interface ErrorResponse {
  error: PublicError;
}
export interface Event {
  id: number;
  event_key: string;
  season: number;
  round: number;
  name: string;
  date: string;
  lifecycle: 'scheduled' | 'postponed' | 'cancelled' | 'completed';
  circuit_name: string | null;
  coverage: Coverage;
}
export interface EventIndex {
  season: number;
  events: Array<Event>;
}
export interface EventSession {
  id: number;
  kind: string;
  scheduled_at: string;
  revision: number;
  status: string;
}
export type ForecastSelection = PublishedForecast | UnavailableForecast;
export interface Freshness {
  state: 'verified_as_of_cutoff' | 'source_late' | 'stale' | 'unknown';
  input_cutoff_at: string | null;
  issued_at: string | null;
  source_available_at: string | null;
  reason: string | null;
}
export interface PublicEntry {
  entry_key: string;
  driver_name: string | null;
  team_name: string | null;
  team_color: string | null;
  win_probability: number | null;
}
export interface PublicError {
  code: 'not_found' | 'invalid_request' | 'api_unavailable' | 'invalid_publication';
  message: string;
  retryable: boolean;
}
export interface PublishedForecast {
  state: 'published';
  reason: null;
  run: PublishedRun;
}
export interface PublishedRun {
  run_id: string;
  season: number;
  event_id: number;
  horizon: 'pre_weekend' | 'post_qualifying';
  published_at: string;
  provenance: 'verified' | 'observed';
  freshness: Freshness;
  coverage: Coverage;
  entries: Array<PublicEntry>;
}
export interface RunIndex {
  season: number;
  event_id: number;
  runs: Array<PublishedRun>;
}
export interface Season {
  year: number;
  ruleset_version: string | null;
  coverage: Coverage;
}
export interface SeasonIndex {
  seasons: Array<Season>;
}
export interface SessionIndex {
  season: number;
  event_id: number;
  sessions: Array<EventSession>;
}
export interface UnavailableForecast {
  state: 'unavailable';
  reason: 'no_published_forecast';
  run: null;
}
