"""Emit deterministic TypeScript DTOs and a JSON-schema snapshot from Pydantic."""

import argparse
import json
from pathlib import Path

from pydantic import TypeAdapter

from api.schemas import public

ROOT = Path(__file__).resolve().parents[1]
MODELS = [
    public.SeasonIndex,
    public.EventIndex,
    public.SessionIndex,
    public.RunIndex,
    public.ErrorResponse,
    public.HistoricalPerformance,
    public.EventPerformance,
    public.LivePerformance,
]


def ts(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(repr(item) for item in schema["enum"])
    if "const" in schema:
        return repr(schema["const"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }[kind]


def outputs():
    definitions = {}
    for model in MODELS:
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[model.__name__] = schema
    selection = TypeAdapter(public.ForecastSelection).json_schema()
    definitions.update(selection.pop("$defs", {}))
    definitions["ForecastSelection"] = selection
    lines = ["// Generated by scripts/generate_public_client.py. Do not edit manually."]
    for name, schema in sorted(definitions.items()):
        if "properties" not in schema:
            lines.append(f"export type {name} = {ts(schema)};")
            continue
        lines.append(f"export interface {name} {{")
        # Defaults serialize in responses, so clients always receive every property.
        for key, value in schema["properties"].items():
            rendered = ts(value)
            if len(f"  {key}: {rendered};") > 100 and " | " in rendered:
                lines.append(f"  {key}:")
                choices = rendered.split(" | ")
                lines.extend(f"    | {choice}" for choice in choices[:-1])
                lines.append(f"    | {choices[-1]};")
            else:
                lines.append(f"  {key}: {rendered};")
        lines.append("}")
    return {
        ROOT / "dashboard/src/public/contract.ts": "\n".join(lines) + "\n",
        ROOT / "docs/api/public-v1.schema.json": json.dumps(
            {"$defs": definitions}, sort_keys=True, indent=2
        )
        + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = outputs()
    generated[ROOT / "dashboard/src/public/schema.json"] = generated[
        ROOT / "docs/api/public-v1.schema.json"
    ]
    for path, content in generated.items():
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f"Stale generated contract: {path}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
