/* Production-build browser QA; only the explicitly synthetic WP12 fixture is used. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.WP12_PREVIEW_URL || 'http://127.0.0.1:4173';
const evidence = path.resolve(__dirname, '../docs/design/evidence/wp12');
const axe = process.env.AXE_PATH || '/private/tmp/wp12-browser-tools/node_modules/axe-core/axe.min.js';
fs.mkdirSync(evidence, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
  const page = await context.newPage();
  const report = { fixture: 'WP12 synthetic forecast/correction database; historical metrics are the actual retained WP09 evaluation', checks: [], screenshots: [], accessibility: [], pageErrors: [] };
  page.on('pageerror', error => report.pageErrors.push(error.message));
  const requests = [];
  page.on('request', r => requests.push(r.url()));
  const record = (name, details = {}) => report.checks.push({ name, passed: true, ...details });
  const shot = async name => { await page.screenshot({ path: path.join(evidence, name + '.jpg'), fullPage: true, type: 'jpeg', quality: 82 }); report.screenshots.push(name + '.jpg'); };
  const open = async (url, title) => { await page.goto(base + url); await page.getByRole('heading', { name: title, exact: true }).waitFor(); };
  const audit = async name => { await page.addScriptTag({ path: axe }); const result = await page.evaluate(async () => (await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } }))); report.accessibility.push({ name, violations: result.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => n.target) })), incomplete: result.incomplete.map(v => v.id) }); assert.equal(result.violations.length, 0, JSON.stringify(report.accessibility.at(-1))); record('axe WCAG A/AA: ' + name); };
  const full = '/seasons/2022/events/2022/field';
  await open(full, 'Horizon and revision comparison');
  await page.getByRole('region', { name: 'Full-field win probability comparison' }).waitFor();
  await page.reload(); await page.getByRole('region', { name: 'Full-field win probability comparison' }).waitFor();
  const comparison = page.getByRole('region', { name: 'Full-field win probability comparison' });
  assert.equal(await comparison.locator('tbody tr').count(), 22);
  assert.match(await comparison.innerText(), /20%\s+25%\s+\+5.0 percentage points/);
  assert.match(await comparison.innerText(), /0%\s+0%\s+No change at displayed precision/);
  assert.match(await comparison.innerText(), /Unknown\s+Unknown\s+Not available/);
  assert.doesNotMatch(await page.locator('body').innerText(), /internal_secret|private-evaluation|Current roster|Current brand|NaN/);
  assert(await comparison.locator('tbody th').first().evaluate(e => e.getBoundingClientRect().width >= 180));
  record('Text headers have readable width instead of the inherited narrow rank column');
  record('Stored 20% to 25% official win chance gives +5.0 percentage points; zero and unavailable distinct; 22 entries');
  await page.getByLabel('Driver', { exact: true }).selectOption({ index: 2 });
  const driverPanel = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Driver detail', exact: true }) });
  assert.match(await driverPanel.innerText(), /Official race win chance: Unknown/);
  record('Driver detail retains unknown winner probability and explains unsupported position/retirement outcomes');
  assert(!requests.some(url => /BarChart-/.test(url)));
  await page.getByRole('button', { name: 'Show probability chart' }).click();
  await page.getByRole('heading', { name: 'Published win probability distribution' }).waitFor();
  assert(requests.some(url => /BarChart-/.test(url)));
  record('Optional chart remains lazy with accessible full-field table');
  await page.getByRole('button', { name: 'Hide probability chart' }).click();
  await shot('forecast-comparison'); await audit('forecast comparison light');
  await page.emulateMedia({ colorScheme: 'dark' }); await shot('forecast-dark'); await audit('forecast comparison dark');
  await page.emulateMedia({ colorScheme: 'light' });
  await page.getByLabel('Reference', { exact: true }).selectOption('');
  assert.match(await page.locator('body').innerText(), /Both selected snapshots are required/);
  record('Missing comparison selection does not fabricate a probability change');

  await open('/seasons/2022/record', 'Out-of-sample historical reconstruction');
  await page.getByLabel('Inspect stored model').waitFor();
  const scorecard = page.getByRole('region', { name: 'Historical model and baseline scorecard' });
  const standings = scorecard.locator('tr').filter({ hasText: 'Race-only standings baseline' });
  assert.match(await standings.innerText(), /1.903398\s+42.9%\s+70\/70/);
  assert.match(await page.locator('body').innerText(), /not a pristine holdout|not prospective/);
  await page.getByText('All historical race results and exclusions', { exact: true }).click();
  assert.equal(await page.getByRole('region', { name: 'Historical race result comparison' }).locator('tbody tr').count(), 70);
  const ids = await page.getByRole('region', { name: 'Historical race result comparison' }).locator('tbody th').allTextContents();
  assert(ids.includes('2023 / 12')); assert(ids.includes('2023 / 6')); assert(ids.includes('2023 / 22')); assert(!ids.includes('2023 / 23'));
  record('Historical score equals stored winner loss/hit rate; all 70 races and stored season/round identifiers visible without renumbering');
  await page.getByText('All historical race results and exclusions', { exact: true }).click();
  await shot('historical-scorecard'); await audit('historical scorecard');
  await page.getByLabel('Evaluation horizon').selectOption('post_qualifying');
  await page.getByLabel('Inspect stored model').selectOption('Qualifying-order baseline');
  const qualifying = page.getByRole('region', { name: 'Historical model and baseline scorecard' }).locator('tr').filter({ hasText: 'Qualifying-order baseline' });
  assert.match(await qualifying.innerText(), /1.737578\s+61.4%\s+70\/70/);
  record('Separate after-qualifying stored cohort and retained fallback; baseline comparisons preserved');
  await shot('post-qualifying-scorecard');

  await open('/seasons/2022/events/2022/results', 'Results and correction history');
  assert.match(await page.locator('body').innerText(), /1.609438|3.167583/);
  assert.match(await page.locator('body').innerText(), /Result revision 3/);
  assert.match(await page.locator('body').innerText(), /Earlier scores do not represent this result revision/);
  record('Original run/result revision pairs retained; latest unscored correction remains unavailable');
  await shot('result-corrections'); await audit('result corrections');
  await page.getByLabel('Evaluation horizon').selectOption('post_qualifying');
  await page.getByText('No public evaluation for this revision.', { exact: false }).first().waitFor();
  assert.equal(await page.getByRole('table').count(), 0);
  record('Unevaluated published horizon never reuses the other horizon score');
  await open('/seasons/2022/methodology', 'Public model card'); await shot('methodology'); await audit('methodology');
  await open('/seasons/2022/sources', 'Sources, coverage and freshness'); await audit('sources');

  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    for (const [url, title] of [[full, 'Horizon and revision comparison'], ['/seasons/2022/record', 'Out-of-sample historical reconstruction'], ['/seasons/2022/events/2022/results', 'Results and correction history'], ['/seasons/2022/methodology', 'Public model card'], ['/seasons/2022/sources', 'Sources, coverage and freshness']]) {
      await open(url, title); await page.locator('h1').waitFor();
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      record('Reflow ' + width + ': ' + url);
    }
    await open(full, 'Horizon and revision comparison');
    await page.getByRole('region', { name: 'Full-field win probability comparison' }).focus(); await page.keyboard.press('ArrowRight');
    await shot('mobile-' + width); await audit('mobile forecast ' + width);
  }
  await page.getByRole('link', { name: 'Skip to main content' }).focus(); await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'main');
  await page.getByRole('button', { name: /After qualifying/ }).focus(); await page.keyboard.press('Space');
  await page.getByRole('table').first().waitFor();
  await page.getByRole('link', { name: 'Results and corrections', exact: true }).focus(); await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: 'Results and correction history' }).waitFor();
  assert.equal(await page.evaluate(() => document.activeElement.tagName), 'H1');
  record('Keyboard skip, horizon, results navigation and heading focus');
  await page.getByRole('combobox', { name: 'Season', exact: true }).selectOption('2026');
  await page.waitForURL(/\/seasons\/2026\//); await page.getByRole('heading', { name: 'Horizon and revision comparison' }).waitFor();
  assert.doesNotMatch(await page.locator('body').innerText(), /Fixture Driver .*2022/);
  record('Season switching cancels old context without retaining previous roster/scores');

  const actual = await (await context.request.get(base + '/api/v1/seasons/2022/events/2022/runs')).json();
  const changed = structuredClone(actual); changed.runs[0].entries[0].entry_key = 'entry:changed';
  await page.route('**/events/2022/runs', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify(changed) }));
  await open(full, 'Horizon and revision comparison');
  await page.getByText('The entry field changed.', { exact: false }).waitFor();
  assert.doesNotMatch(await page.getByRole('region', { name: 'Full-field win probability comparison' }).innerText(), /\+5.0 percentage points/);
  record('Changed entry revision suppresses incomparable deltas and preserves original values');
  await page.unroute('**/events/2022/runs');
  await page.route('**/performance?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'api_unavailable', message: 'Synthetic evaluation service unavailable', retryable: true } }) }));
  await open('/seasons/2022/events/2022/results', 'Could not load data');
  assert.equal(await page.getByRole('table').count(), 0);
  await shot('evaluation-error'); record('Performance error shows Retry without retained scores');
  await page.unroute('**/performance?*'); await page.getByRole('button', { name: 'Retry' }).click();
  await page.getByRole('heading', { name: 'Results and correction history' }).waitFor();
  record('Performance Retry restores original stored revision history');
  assert.deepEqual(report.pageErrors, []);
  fs.writeFileSync(path.join(evidence, 'browser.json'), JSON.stringify(report, null, 2) + '\n');
  await browser.close();
  console.log(JSON.stringify({ checks: report.checks.length, screenshots: report.screenshots.length, accessibility: report.accessibility.length, pageErrors: report.pageErrors }));
})().catch(error => { console.error(error); process.exit(1); });
